### ISSUE TITLE
ZMap does not operate through VPN Tunnels

### ISSUE THREAD

**Issue by skunkwerk** [zmap/zmap#316]
I am running as sudo on Mac OS X, with an openvpn client running.

The error I'm getting is:
Dec 31 21:03:54.817 [FATAL] send: could not retrieve hardware address for interface: utun0

I'm running with this command:
sudo /usr/local/sbin/zmap -p 80 -w us_whitelist_1.txt --bandwidth=10M --vpn -i utun0 -o output.csv

This is my ifconfig:
utun0: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1500
    inet 192.253.240.103 --> 192.253.240.103 netmask 0xffffffe0 
    nd6 options=1<PERFORMNUD>

Any suggestions on how to get this to work?

**Comment by dadrian** [comment]
Unfortunately, I think `--vpn` may be totally broken. Can you try setting a gateway MAC address with `-G`, even if the network isn't using Layer 2? What's the output of `arp -a`?

**Comment by zakird** [comment]
I've been playing with this for the last several days and have gotten ZMap to send/receive properly with IP layer packets. The errors you receive on initialization are no longer present and we're able to successfully send packets across tun interfaces. These changes are all present in the `vpn-great-again` branch. 

he main issue I'm running into here is that I can find no way (even after almost a days worth of research) to run pcap against a tunnel interface. No matter what interface you choose, you don't seem to have access to the unencrypted packets. If someone knows of a way of capturing these packets, I'm all ears, but at this point I think I have to call it on how much more time I spend looking at this given that it's a pretty esoteric feature given the scope of ZMap.

**Comment by zakird** [comment]
Looking back at my notes, it looks like we have the code to send IP level packets, but can't capture responses because libpcap doesn't play well with these tunnel interfaces.  ZMap is fundamentally built on top of libpcap to receive and process probe packets. At this time, I don't think it's within scope of the project to change this. As such, I am closing this issue.

**Comment by drmckay** [comment]
> Looking back at my notes, it looks like we have the code to send IP level packets, but can't capture responses because libpcap doesn't play well with these tunnel interfaces. ZMap is fundamentally built on top of libpcap to receive and process probe packets. At this time, I don't think it's within scope of the project to change this. As such, I am closing this issue.

Hi,

I have the same issue with VPN (PtP) tunnel interfaces. However, I tested it and found that the following filter is problematic:
https://github.com/zmap/zmap/blob/master/src/probe_modules/module_tcp_synscan.c#L171

As I see, this filter passed to the pcap_compile function on the following link:
https://github.com/zmap/zmap/blob/master/src/recv-pcap.c#L110

So for further analysis, I tried this filter with tcpdump, because tcpdump and zmap are loading the same libpcap library:

```sh
# tcpdump -i ppp0 -n "tcp && tcp[13] & 4 != 0 || tcp[13] == 18"
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on ppp0, link-type LINUX_SLL (Linux cooked), capture size 262144 bytes
13:29:49.928529 IP 3.121.123.163.15064 > 178.164.197.14.39122: Flags [S.], seq 2640062884, ack 3424777179, win 26847, options [mss 1460,sackOK,TS val 927174012 ecr 154593519,nop,wscale 12], length 0
13:29:50.126513 IP 178.164.197.14.54725 > 162.125.19.130.443: Flags [R.], seq 2122791507, ack 525550236, win 0, length 0
13:29:52.466841 IP 172.217.18.74.443 > 178.164.197.14.60670: Flags [S.], seq 1023303438, ack 1623968212, win 60192, options [mss 1380,sackOK,TS val 3378195329 ecr 110707658,nop,wscale 8], length 0
13:29:52.668663 IP 172.217.18.74.443 > 178.164.197.14.60672: Flags [S.], seq 1823051201, ack 2317603400, win 60192, options [mss 1380,sackOK,TS val 3239382883 ecr 110707709,nop,wscale 8], length 0
```

Well, tcpdump compiled the filter without any issue and it works with libpcap on ppp interface, quite well. Therefore, I attached GDB to zmap and found something interesting:

```gdb
Thread 2 "zmap" hit Breakpoint 3, 0x004137d0 in recv_init ()
(gdb) i r
r0             0xb60004c8       3053454536
r1             0xb6984914       3063433492
r2             0xb6984a1c       3063433756
r3             0x1      1
r4             0xb60004c8       3053454536
r5             0x0      0
r6             0x444dc8 4476360
r7             0xb698491c       3063433500
r8             0xb6ffece8       3070225640
r9             0xb6984914       3063433492
r10            0x4346a0 4408992
r11            0x0      0
r12            0xb6984a69       3063433833
sp             0xb69848f0       0xb69848f0
lr             0x29     41
pc             0x4137d0 0x4137d0 <recv_init+232>
cpsr           0x30     48
(gdb) x/s 0xb6984914
0xb6984914:     ""
(gdb) x/s 0xb6984a1c
0xb6984a1c:     "not ether src 00:00:00:00:00:00 and (tcp && tcp[13] & 4 != 0 || tcp[13] == 18)"
```

Thus, I wrote a simple C app to get further information about the error:

```C
#include <stdio.h>
#include <string.h>
#include <pcap.h>

pcap_t *handle;         /* Session handle */
struct bpf_program bpf;         /* The compiled filter expression */
char errbuf[PCAP_ERRBUF_SIZE];  /* Error string */
unsigned char bpftmp[1024];
char dev[] = "ppp0";

int main() {

        bpftmp[0] = 0;
        strcat(bpftmp, "not ether src 00:00:00:00:00:00 and (");
        strcat(bpftmp, "tcp && tcp[13] & 4 != 0 || tcp[13] == 18");
        strcat(bpftmp, ")");

        handle = pcap_open_live(dev, BUFSIZ, 1, 1000, errbuf);
        if (handle == NULL) {
                fprintf(stderr, "Couldn't open device %s: %s\n", dev, errbuf);
                return(2);
        }

        if (pcap_compile(handle, &bpf, bpftmp, 0, 1) == -1) {
                fprintf(stderr, "Couldn't parse filter %s: %s\n", bpftmp, pcap_geterr(handle));
                return(2);
        }

}
```

The compiled test_pcap application gives a better understanding of the error:
```sh
# gcc -o test_pcap -lpcap test_pcap.c
# ./test_pcap
Couldn't parse filter not ether src 00:00:00:00:00:00 and (tcp && tcp[13] & 4 != 0 || tcp[13] == 18): ethernet addresses supported only on ethernet/FDDI/token ring/802.11/ATM LANE/Fibre Channel
```
The aforementioned recv_pcap.c file code block contains modifications to bypass the unnecessary filter rules and we can use the zmap's -X parameter to send IP packets only, but in this case I think this parameter won't affect the application behaviour somehow.
