### ISSUE TITLE
Data lenght condition same as X bytes.

### ISSUE THREAD

**Issue by Alemalakra** [zmap/zmap#531]
Hey, i need some help with the thing of "Output filter", Basically i want to save only IP's of scanned result have X bytes exactly, So that is, i tried so much and i need help with that, i tired this.

` zmap -M udp -p XXXPORT --probe-args=file:payload_data.pkt -r 100000 --output-filter="udp_pkt_size = 5"` because all packets lenght reply gonna be 5, i tired chaning "udp_pkt_size" to "data", What i'm doing wrong? Thanks for advance.

**Comment by zakird** [comment]
What happens when you don't have this filter? Do the packets have an output length of 5 or something else? Given that the 5 is smaller than the minimum UDP packet header length (and UDP packet length header includes the entire UDP packet), I don't imagine any packets will have that length. You could either add another field that includes the length of the UDP payload or post-process this.
