### ISSUE TITLE
How to output the response rst packet?

### ISSUE THREAD

**Issue by hmimy5416** [zmap/zmap#542]
I want to output the rst packet, use  -f "response" , [FATAL] fieldset: specified field (response) not available in selected probe module, how to output the rst packet?

**Comment by ihotep** [comment]
I am having same problem while scanning for alive hosts (default SYN scan) to consider alive when ACK or RST received. Everything is fine with ACK reported as "success" but I have no clue how to get RST hosts aswell, because I am getting same error while filtering output: [FATAL] fieldset: specified field (response) not available in selected probe module, how to output the rst packet?

**Comment by zakird** [comment]
You can get this by setting `--output-module=csv` and using no output filter (or setting one as you see fit). There is some documentation about output filters here: https://github.com/zmap/zmap/wiki/Results-Output.
