### ISSUE TITLE
can zmap support sending packets on one host and receiving on another?

### ISSUE THREAD

**Issue by benbusi** [zmap/zmap#566]
I am curious if zmap can support sending packets on one host and then receiving packets on another host？If it can, what command Ishould use?

**Comment by zakird** [comment]
Nothing prevents this since packets sent are constructed from the ethernet layer up. You can use libpcap, tcpdump, or any other utility you need on the other server to capture the responses. The ZMap executable itself doesn't have a flag that prevents sending that would be needed if you wanted to use that directly, but you could pretty easily add a flag that just doesn't start the send threads and instead runs until you stop it.
