### ISSUE TITLE
How does Shards work

### ISSUE THREAD

**Issue by 0xCC00FFEE** [zmap/zmap#581]
Hello,

Sorry if the question might seem trivial, but I couldn't find much about it or anything that may answer my questions whether in Zmap's wiki pages, or by Googling.

So I wanted to ask how does shards work and what's the relationship between `--shard` and `--seed`? If I wanted to divide a simple port 80 internet-wide scan between 8 machines, shall the command executed on each machine be as the following:
Machine1:
```
# zmap 0.0.0.0/0 -p80 --shards=8 --shard=0 --seed=1234
```
Machine2:
```
# zmap 0.0.0.0/0 -p80 --shards=8 --shard=1 --seed=1234
```
Machine3:
```
# zmap 0.0.0.0/0 -p80 --shards=8 --shard=2 --seed=1234
```
And so on, is that the correct usage for my use case?

**Comment by zakird** [comment]
Yes, that's correct. All should have the same seed and blacklist. shards is the number of shards you'll have in total and shard is the id of that specific shard.

**Comment by 0xCC00FFEE** [comment]
Thank you!

**Comment by thefirst100yearsaredifficult** [comment]
Hello, 
sorry for commenting on such an old issue but since my question is simillar I didn't want to create a new one. If you have 8 machine and you start with --shard=0 on the first one then on the eighth you will have --shard=7 thus having 8. My question is the correct way to impliment shards is like this:

**example 1**
zmap 0.0.0.0/0 -p80 --shards=8 --shard=0 --seed=1234
zmap 0.0.0.0/0 -p80 --shards=8 --shard=0 --seed=1234
zmap 0.0.0.0/0 -p80 --shards=8 --shard=0 --seed=1234
zmap 0.0.0.0/0 -p80 --shards=8 --shard=0 --seed=1234
