### ISSUE TITLE
PFRING ZC Not Working with ZMAP

### ISSUE THREAD

**Issue by stanley111111** [zmap/zmap#694]
https://github.com/ntop/PF_RING/issues/818

Any ideas why PFRING ZC doesn't seem to work with ZMAP? Anyone had any luck with the 10gbe driver? :)

**Comment by dadrian** [comment]
The PF_RING code is almost a decade old at this point, and I no longer have access to a test setup for it. I assume we need code updates for it. ZMap implementation requires recompiling from source and setting a custom build flag, so make sure you're testing with that.

**Comment by icuceee** [comment]
error from dmesg launching pfring

[  106.871619] [PF_RING] pf_ring initialized correctly
Trying to map ZC device eno1@0
[  397.814776] [PF_RING] pfring_select_zc_dev:6301 eno1@0 mapping failed or not a ZC device

dmesg shows error when launching with pfring

CentOS Linux release 7.9.2009 (Core)
latest pfring driver

**Comment by davideandres95** [comment]
I have found out several things in relation to this issue, one of them being a bug.

In first place, when support for cooked mode was introduced (#504 ), PF_RING was left behind. The culprit being https://github.com/zmap/zmap/blob/c4931bd5c109a7168629c902ffaca26204906229/src/recv.c#L45 as the ethernet header is expected to be there.

A possible solution I have tested would be to set `zconf.data_link_size` inside `recv-pfring.c:recv_init`:
```
void recv_init()
{
	// Get the socket and packet handle
	pf_recv = zconf.pf.recv;
	pf_buffer = pfring_zc_get_packet_handle(zconf.pf.cluster);
	if (pf_buffer == NULL) {
		log_fatal("recv", "Could not get packet handle: %s",
			  strerror(errno));
	}
	zconf.data_link_size = sizeof(struct ether_header);
}
```
Without it, headers are not parsed correctly and no packets passes validation.

In second place, packets are never actively flushed, and queues are only synced upon termination. While the sync should flush any small number of packets unsent when the sender finishes, I have tested that if a single probe to a single target is scheduled, no packet will be sent out. Increasing the number of probes above 512 flushes them automatically, so for large scans I believe packets will be sent. But any number of remaining packets (<512) at the end will be possibly not sent out.

After looking into the PF_RING_ZC examples, I believe that queues should be synced within the timing-delay loop so that no packets are kept buffered while waiting, but I am a beginner in this area and I leave it up to you how this should be handled. As a workaround, I am flushing every single packet individually, which will degrade performance but will improve the latency observed by my probes, which is for my use-case relevant (latency measurements).
