### ISSUE TITLE
Hitrate dropping with each successive CIDR block included in scan

### ISSUE THREAD

**Issue by cohogan** [zmap/zmap#718]
Sorry if I'm missing something obvious, but I've been experimenting with zmap over the past few days, and I've noticed that with each CIDR block I include in a scan, the hitrate drops.

For example, for each of these commands, I'll get a hitrate of ~15%.
`zmap --probe-module=icmp_echoscan x.x.x.0/24`
`zmap --probe-module=icmp_echoscan x.x.y.0/24` 
`zmap --probe-module=icmp_echoscan x.x.z.0/24` 

However, if I run all three blocks in the same command (shown below), my hitrate will stoop to ~4%.
`zmap --probe-module=icmp_echoscan x.x.x.0/24 x.x.y.0/24 x.x.z.0/24`

To my knowledge, the hitrate should remain constant. This seems to be constant no matter which CIDR blocks I scan. Please let me know if there is anything obvious I'm missing, or if there is not enough information in this post to debug. Thanks for the help!

**Comment by zakird** [comment]
It could be that packets are being dropped. In the second case, 3x as many packets are being sent, and because the number of packets being sent is lower than the send rate. While spread across the destination networks, the effective send rate here is much higher on the send side network. I would try manually setting a send rate to be rather small since a local small networks.

**Comment by cohogan** [comment]
Will give it a run. Thank you!
