### ISSUE TITLE
cmake doesn't check for Judy.h

### ISSUE THREAD

**Issue by yurivict** [zmap/zmap#882]
**Describe the bug**

cmake succeeds and the build then fails:

cmake should check all dependencies.

**Environment:**
 - OS: FreeBSD 14.0
 - Version: 4.1.1

**Comment by phillip-stephens** [comment]
IMO, I'm not sure this is a bug but rather a potential enhancement. It'd be _nice_ if CMake would give the user a nice message about how `Judy` wasn't found and how to install. But [INSTALL.md](https://github.com/zmap/zmap/blob/main/INSTALL.md#building-from-source) (which is referenced in the README.md) does mention exactly what you need to install to compile this from source.

I'll take a look at getting this into CMake though since it would improve the user experience.

**Comment by yurivict** [comment]
cmake can easily check for the header with [CHECK_INCLUDE_FILE](https://cmake.org/cmake/help/latest/module/CheckIncludeFile.html).
